name: CD Production
on:
  workflow_run:
    workflows: ["CI Staging"]
    branches: ["main"]
    types: [completed]

jobs:
  deploy-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}  # 👈 Chave separada
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1

      - name: Terraform Apply
        run: |
          cd terraform/production
          terraform init
          terraform apply -auto-approve