name: CI Staging
on: [push]
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Apply
      env:
        TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
        TF_VAR_my_ip: ${{ secrets.TF_VAR_MY_IP }}
      run: |
        cd terraform/staging
        terraform init
        terraform apply -auto-approve