name: CI Staging
on:
  push:
    branches: [ "test-ci" ]
  workflow_dispatch:  # Permite acionar manualmente

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          cd terraform/staging
          terraform init -input=false
          terraform validate

      - name: Terraform Apply
        id: apply 
        run: terraform apply --auto-approve
  
      - name: Get Instance Public IP
        id: get_ip 
        run: echo "instance_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: app/Dockerfile
          push: true
          tags: janainagois/lacrei-app:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.get_ip.outputs.instance_ip }} 
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker pull janagois/desafio-lacrei-devops:latest
            sudo docker run -d --name lacrei -p 80:80 janagois/desafio-lacrei-devops:latest