name: Destroy Staging

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -backend-config="../../backend-staging.conf"
        working-directory: terraform/staging

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/staging

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=".terraform/terraform.tfvars"
        working-directory: terraform/staging

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=".terraform/terraform.tfvars"
        working-directory: terraform/staging